# ── Nombre de la app ──────────────────────────────────────
spring.application.name=rambedcash

# ── Conexión a PostgreSQL ─────────────────────────────────
spring.profiles.active=local

# ── JPA / Hibernate ───────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ── Puerto del servidor ───────────────────────────────────
server.port=8080


# ── Datos de la empresa ───────────────────────────────────
app.empresa.nombre=Rambed
app.empresa.sector=Textil